# Generated by Django 4.0.3 on 2022-04-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_message', models.CharField(max_length=256)),
                ('first_message', models.CharField(max_length=256)),
                ('second_message', models.CharField(max_length=256)),
                ('third_message', models.CharField(max_length=256)),
            ],
        ),
    ]
