# Generated by Django 4.0.3 on 2022-04-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='home_skin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
