# Generated by Django 4.0.3 on 2022-04-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_home_first_message_alter_home_second_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='topic_first_message',
            field=models.CharField(default=1, max_length=26),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='topic_second_message',
            field=models.CharField(default=1, max_length=26),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='topic_third_message',
            field=models.CharField(default=1, max_length=26),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='topic_welcome_message',
            field=models.CharField(default=1, max_length=26),
            preserve_default=False,
        ),
    ]
