# Generated by Django 4.0.3 on 2022-04-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_home_first_message_alter_home_home_skin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='topic_welcome_message',
        ),
    ]
