# Generated by Django 4.0.3 on 2022-04-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_appuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_staff',
        ),
    ]
