# Generated by Django 4.0.3 on 2022-04-15 17:04

import django.core.validators
from django.db import migrations, models
import eventhub.user_auth.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_alter_appuser_first_name_alter_appuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(default='', max_length=15, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(15), eventhub.user_auth.validators.only_letters_validator]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(default='', max_length=15, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(15), eventhub.user_auth.validators.only_letters_validator]),
        ),
    ]
