# Generated by Django 4.0.3 on 2022-04-11 08:27

import django.core.validators
from django.db import migrations, models
import eventhub.categories.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(15), eventhub.categories.validators.only_letters_validator])),
                ('category_description', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(35), eventhub.categories.validators.only_letters_validator])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', validators=[eventhub.categories.validators.MaxFileSizeInMbValidator(2)])),
            ],
        ),
    ]
